ALTER TABLE bank_users ADD COLUMN auth_version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE bank_users ADD COLUMN email_assurance VARCHAR(16) NOT NULL DEFAULT 'UNVERIFIED';
ALTER TABLE bank_users ADD COLUMN phone_assurance VARCHAR(16) NOT NULL DEFAULT 'UNVERIFIED';
ALTER TABLE auth_tokens ADD COLUMN auth_version BIGINT NOT NULL DEFAULT 0;
CREATE TABLE identity_gate(id INTEGER PRIMARY KEY);
INSERT INTO identity_gate(id) VALUES(1);
CREATE TABLE contact_challenges(
 id VARCHAR(36) PRIMARY KEY,user_id BIGINT REFERENCES bank_users(id),purpose VARCHAR(16) NOT NULL,
 channel VARCHAR(8) NOT NULL,contact_encrypted TEXT NOT NULL,contact_lookup VARCHAR(64) NOT NULL,
 code_hash VARCHAR(64) NOT NULL,code_encrypted TEXT,inbox_hash VARCHAR(64) NOT NULL,
 grant_hash VARCHAR(64) UNIQUE,expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
 grant_expires_at TIMESTAMP(6) WITH TIME ZONE,failures INTEGER NOT NULL DEFAULT 0,
 verified BOOLEAN NOT NULL DEFAULT FALSE,consumed BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_contact_lookup ON contact_challenges(purpose,channel,contact_lookup);
CREATE TABLE recovery_codes(code_hash VARCHAR(64) PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES bank_users(id),created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,consumed BOOLEAN NOT NULL DEFAULT FALSE);
CREATE INDEX idx_recovery_user ON recovery_codes(user_id);
CREATE TABLE identity_rates(id VARCHAR(64) PRIMARY KEY,until TIMESTAMP(6) WITH TIME ZONE NOT NULL,attempts INTEGER NOT NULL);
CREATE TABLE registration_receipts(id VARCHAR(36) PRIMARY KEY,request_hash VARCHAR(64) NOT NULL,customer_id VARCHAR(36) NOT NULL);
CREATE TABLE terms_consents(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES bank_users(id),term_id VARCHAR(32) NOT NULL,term_version VARCHAR(32) NOT NULL,accepted_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,UNIQUE(user_id,term_id,term_version));
