CREATE TABLE savings_contracts(
 id VARCHAR(36) PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES bank_users(id),account_id BIGINT NOT NULL UNIQUE REFERENCES accounts(id),
 product_id VARCHAR(24) NOT NULL,terms_version VARCHAR(32) NOT NULL,accepted_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
 opened_on DATE NOT NULL,maturity_on DATE NOT NULL,months INTEGER NOT NULL,annual_rate NUMERIC(8,6) NOT NULL,early_rate NUMERIC(8,6) NOT NULL,
 installment NUMERIC(19,2) NOT NULL,status VARCHAR(16) NOT NULL,version BIGINT NOT NULL,closed_on DATE
);
CREATE INDEX idx_savings_owner ON savings_contracts(user_id);
CREATE TABLE savings_payments(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,contract_id VARCHAR(36) NOT NULL REFERENCES savings_contracts(id),period_index INTEGER NOT NULL,paid_on DATE NOT NULL,amount NUMERIC(19,2) NOT NULL,UNIQUE(contract_id,period_index));
CREATE TABLE savings_receipts(id VARCHAR(36) PRIMARY KEY,result_encrypted TEXT NOT NULL);
