CREATE TABLE bank_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL
);
CREATE TABLE accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number VARCHAR(255) NOT NULL UNIQUE,
  owner_id BIGINT NOT NULL REFERENCES bank_users(id),
  balance NUMERIC(19,2) NOT NULL DEFAULT 0 CHECK (balance >= 0)
);
CREATE INDEX idx_accounts_owner ON accounts(owner_id);
CREATE TABLE ledger_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL REFERENCES accounts(id),
  counterparty VARCHAR(255) NOT NULL,
  amount NUMERIC(19,2) NOT NULL CHECK (amount <> 0),
  created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  transfer_id VARCHAR(255) NOT NULL
);
CREATE INDEX idx_ledger_account_time ON ledger_entries(account_id,created_at DESC,id DESC);
CREATE TABLE auth_tokens (
  token_hash VARCHAR(255) PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES bank_users(id),
  expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
