CREATE TABLE idempotency_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES bank_users(id),
  request_key VARCHAR(36) NOT NULL,
  request_hash VARCHAR(64) NOT NULL,
  operation VARCHAR(16) NOT NULL,
  result_id VARCHAR(36) NOT NULL,
  created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CONSTRAINT uq_idempotency_user_key UNIQUE (user_id, request_key)
);
