CREATE TABLE transfer_previews (
 id VARCHAR(36) PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES bank_users(id),
 source_id BIGINT NOT NULL REFERENCES accounts(id), target_id BIGINT NOT NULL REFERENCES accounts(id),
 amount NUMERIC(19,2) NOT NULL CHECK(amount>0), snapshot_encrypted TEXT NOT NULL,
 expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL, result_id VARCHAR(36) UNIQUE
);
CREATE TABLE transfer_actions (
 token_hash VARCHAR(64) PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES bank_users(id),
 preview_id VARCHAR(36) NOT NULL REFERENCES transfer_previews(id), purpose VARCHAR(16) NOT NULL,
 expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL, consumed BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE transfer_records (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id VARCHAR(36) NOT NULL UNIQUE, user_id BIGINT NOT NULL REFERENCES bank_users(id),
 preview_id VARCHAR(36) NOT NULL UNIQUE REFERENCES transfer_previews(id),
 amount NUMERIC(19,2) NOT NULL CHECK(amount>0), balance_after NUMERIC(19,2) NOT NULL,
 snapshot_encrypted TEXT NOT NULL, created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_transfer_records_user_time ON transfer_records(user_id,created_at,id);
CREATE INDEX idx_transfer_previews_user ON transfer_previews(user_id);
CREATE INDEX idx_transfer_actions_expiry ON transfer_actions(expires_at);
