-- 역사 자료: v4 스키마. 최신 v5 이전/키 설정은 IMPLEMENTATION_STAGE1.md 참고.
-- SQL 해설본: 읽기 전용 설명 자료. 직접 실행하거나 migration 폴더로 옮기지 마세요.
-- 실행 원본: src/main/resources/db/migration/V1__initial_schema.sql
-- Flyway가 이미 적용한 SQL을 수정하면 체크섬 검증 오류가 발생할 수 있어 별도 파일로 제공합니다.
-- 사용자 표. PRIMARY KEY는 행의 고유 키, IDENTITY는 DB가 번호 자동 생성.
CREATE TABLE bank_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- NOT NULL은 필수, UNIQUE는 중복 불가. 사용자 아이디를 저장한다.
  username VARCHAR(255) NOT NULL UNIQUE,
-- BCrypt 비밀번호 해시를 저장한다.
  password_hash VARCHAR(255) NOT NULL
);
-- 계좌 표. 내부 id와 표시용 number는 서로 다른 값이다.
CREATE TABLE accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- 외부 응답에 쓰는 계좌번호. 중복 저장을 막는다.
  number VARCHAR(255) NOT NULL UNIQUE,
-- REFERENCES는 외래키. 실제 존재하는 사용자의 id만 소유자로 연결한다.
  owner_id BIGINT NOT NULL REFERENCES bank_users(id),
-- NUMERIC(19,2)는 총 19자리·소수 2자리. DEFAULT 0은 기본 잔액, CHECK는 음수 잔액 금지.
  balance NUMERIC(19,2) NOT NULL DEFAULT 0 CHECK (balance >= 0)
);
-- 소유자별 계좌 검색을 돕는 인덱스.
CREATE INDEX idx_accounts_owner ON accounts(owner_id);
-- 입출금 내역 표. 각 행은 계좌 하나에 귀속된다.
CREATE TABLE ledger_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- 거래내역과 계좌를 연결하는 외래키.
  account_id BIGINT NOT NULL REFERENCES accounts(id),
-- 상대 계좌번호 또는 가상 입금 출처.
  counterparty VARCHAR(255) NOT NULL,
-- 0원 내역은 금지. 출금은 음수, 입금은 양수.
  amount NUMERIC(19,2) NOT NULL CHECK (amount <> 0),
-- 시간대가 있는 거래 시각을 저장한다. 소수 초 정밀도는 6자리.
  created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
-- 한 송금의 출금·입금을 연결하는 ID. 두 행이 같은 값을 쓰므로 UNIQUE가 아니다.
  transfer_id VARCHAR(255) NOT NULL
);
-- 계좌별 최신순 조회를 위한 인덱스. DESC는 내림차순.
CREATE INDEX idx_ledger_account_time ON ledger_entries(account_id,created_at DESC,id DESC);
-- 발급 토큰의 해시와 사용자, 만료 시각을 보관한다.
CREATE TABLE auth_tokens (
-- 원본 토큰을 저장하지 않는다. 해시가 기본키다.
  token_hash VARCHAR(255) PRIMARY KEY,
-- 이 토큰을 발급받은 사용자.
  user_id BIGINT NOT NULL REFERENCES bank_users(id),
-- 토큰의 유효 기간을 판단할 만료 시각.
  expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
